version: 2

sources:
  - name: source_database
    database: DEEVAL
    schema: STAGING_UAT  
    tables:
      - name: VTEMP_LOCATION_PROTOTYPE
      - name: TEMP_LEGALENTITY_PROTOTYPE
      - name: TEMP_HUMANENTITY_PROTOTYPE